language: swift
os: osx
osx_image: xcode13.2
xcode_workspace: ./wallet/ECC-Wallet.xcworkspace
xcode_scheme: ECC-Wallet
xcode_destination: platform=iOS Simulator,OS=15.2,name=iPhone 8
addons:
  homebrew:
    packages:
    - sourcery


install:
  - WALLET_DIR=${TRAVIS_BUILD_DIR}/wallet
  - WALLET_WALLET_DIR=${WALLET_DIR}/wallet
  - cp ${WALLET_DIR}/env-vars.sh.example ${WALLET_DIR}/env-vars.sh
  - cd ${WALLET_DIR} ; pod install ; cd ${TRAVIS_BUILD_DIR}

script:
  - set -o pipefail && xcodebuild -version
  - set -o pipefail && xcodebuild -showsdks 
  - travis_wait 60 xcodebuild -quiet -workspace ${TRAVIS_BUILD_DIR}/wallet/ECC-Wallet.xcworkspace -scheme ECC-Wallet-no-logging -destination platform\=iOS\ Simulator,OS\=15.2,name\=iPhone\ 8 build
